include: package:flutter_lints/flutter.yaml

plugins:
  riverpod_lint: 3.1.4

analyzer:
  exclude:
    - lib/**.g.dart
    - lib/**.freezed.dart
    - test/drift/**
    - build/**
    - android/**
    - ios/**

  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    # avoid_print: false  # Uncomment to disable the `avoid_print` rule
    # prefer_single_quotes: true  # Uncomment to enable the `prefer_single_quotes` rule
  